### ISSUE TITLE
maxretrieve clarification

### ISSUE THREAD

**Issue by emanjavacas** [INL/BlackLab-server#6]
I noticed that whenever I want to paginate over hits increasing param "first" by a user-defined page size, it works as expected until I reach the hit number "defaultMaxHitstoRetrieve" (20) (or "maxretrieve" if given in ajax params), but after that I keep getting the first page. So, basically I can only get as many hits as specified by maxretrieve/defaultMaxHitsToRetrieve. I think I understand how this works, but I am wondering why is the default such a low number and what could advice against setting this to unlimited (if  I want to let users explore the entire search results)? Perhaps there is a different way for pagination that I am missing?

best

**Comment by jan-niestadt** [comment]
Yes, the documentation right now contains unrealistically low numbers, sorry about that. I think those are left over from testing. I'll update them to be a bit more sensible. 

maxHitsToRetrieveAllowed exists because of sorting and grouping, mostly. For those operations, you need to fetch all the hits, which can put a heavy load on a server for complex queries with many hits. Setting maxHitsToRetrieveAllowed and defaultMaxHitsToRetrieve to unlimited will ensure that you won't miss any results, but may make the server really slow.

It depends on your corpus size and usage patterns, of course. We have corpora of 500M+ tokens and groups of students performing complicated searches with millions of hits at the same time, so we ran into problems.

**Comment by emanjavacas** [comment]
Thanks for the info, I see and appreciate the care taken for handling this type of situation :-)
